[target.riscv32imc-unknown-none-elf]
# for running the tests with probe-rs
runner = "probe-rs run --chip esp32c3"
rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C",
    "force-frame-pointers",
]

[env]
ESP_LOG = "debug"
DEFMT_LOG = "debug"

[alias]
integration-tests = "test --test integration --target riscv32imc-unknown-none-elf"
integration-mock-tests = "llvm-cov test --test integration_mock"
integration-mock-tests-ci = "llvm-cov test --test integration_mock --all-features --lcov --output-path lcov.info"
