[target.riscv32imc-unknown-none-elf]
# for running the tests with probe-rs
runner = "probe-rs run --chip esp32c3"

[env]
ESP_LOG = "debug"
DEFMT_LOG = "debug"

[build]
rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C",
    "force-frame-pointers",
]

[alias]
integration-tests = "test --test integration --target riscv32imc-unknown-none-elf"
