name: Main CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
          - command: doc
            args: --all-features
          - command: publish
            args: --dry-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: stable
          components: rust-src, rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command 'cargo ${{ matrix.action.command }}''
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: stable
          components: rust-src, rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests and generate code coverage
        run: cargo integration-mock-tests-ci
